name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

# GitHub Token に対して書き込み権限を明示的に付与
permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          # フル履歴を取り、credentials を維持して push できるようにする
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd wev
          npm ci

      - name: Build
        run: |
          cd wev
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: wev/dist
          # 必要なら publish_branch を指定：
          # publish_branch: gh-pages
